### ISSUE TITLE
Urdu Translations of  Muhammad Junagarhi  and Fateh Muhammad Jalandhry 

### ISSUE THREAD

**Issue by khanra01** [pmossie/QuranLO#2]
MashaAllah a very useful plugin. May Allah benefit you with best in this World and hereafter. I am suing it to make notes for my lectures in Quran. Request you to kindly include the two translations in Urdu language. These translations are available on tanzil.net. I need them desperately specially in this month of 
Ramadan as my Quran lectures are in Urdu language also.

**Comment by pmossie** [comment]
I am glad you like it. I will see what I can do. As it is Ramadan, I don't do a lot of work on my computer. My translation option does need to be extended with the capability to RightToLeft writing. It now defaults to LeftToRight. So I need to rework the design a bit. 
Regards Mossie

**Comment by pmossie** [comment]
I have added the Urdu translation. I will shortly upload it to the libreoffice plugin website. It will take a few days before it will available there. In the meantime you can download the oxt file from the dist folder and install it manually.
I would welcome any feedback.

May Allah support you in your Quran lectures. 
Wasalaam Mossie
